algo = input("Digite algo: ")
print("O tipo primitivo desse valor é {}".format(type(algo)))
print("Tem apenas espaços? {}".format(algo.isspace()))
print("É um número? {}".format(algo.isnumeric()))
print("É alfabético? {}".format(algo.isalpha()))
print("É alfanúmerico? {}".format(algo.isalnum()))
print("Tá em maiúsculas? {}".format(algo.isupper()))
print("Tá em minúsculo? {}".format(algo.islower()))
print("Tá capitalizada? {}".format(algo.istitle()))